### ISSUE TITLE
pandas-stubs resulting in mypy to fail at initialization

### ISSUE THREAD

**Issue by jindongyang94** [pandas-dev/pandas-stubs#1019]
**Describe the bug**
mypy is unable to run with the following error when pandas-stubs is installed. The error is as following:
Traceback (most recent call last):
  File "/code/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
             ^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 102, in main
  File "mypy/main.py", line 186, in run_build
  File "mypy/build.py", line 194, in build
  File "mypy/build.py", line 269, in _build
  File "mypy/build.py", line 2935, in dispatch
  File "mypy/build.py", line 3333, in process_graph
  File "mypy/build.py", line 3460, in process_stale_scc
  File "mypy/build.py", line 2497, in write_cache
  File "mypy/build.py", line 1559, in write_cache
  File "mypy/nodes.py", line 390, in serialize
  File "mypy/nodes.py", line 4010, in serialize
  File "mypy/nodes.py", line 3947, in serialize
  File "mypy/nodes.py", line 3371, in serialize
  File "mypy/types.py", line 682, in serialize
  File "mypy/types.py", line 2475, in serialize
  File "mypy/types.py", line 1498, in serialize
  File "mypy/types.py", line 682, in serialize
  File "mypy/types.py", line 3160, in serialize
AssertionError: Internal error: unresolved placeholder type None

When pandas-stubs is uninstalled, the following result will be seen:
Success: no issues found in 1 source file

When a different command is ran with pandas-stubs installed, the following result will be seen:
Success: no issues found in 1 source file

**To Reproduce**
1. pip install pandas-stubs & mypy in a python3.11 virtual environment
2. run command `mypy -c 'import pandas as pd'` - this will fail
3. run command `mypy -c 'import os'` - this will pass

**Please complete the following information:**
 - OS: Linux (Windows WSL2)
 - OS Version - Ubuntu 22.04.2 LTS
 - python version 3.11.10
 - version of type checker - mypy: 1.13.0 & mypy-extensions: 1.0.0
 - version of installed `pandas-stubs` - pandas-stubs-2.2.3.241009

**Additional context**
pre-commit is working but likely it is due to not having pandas-stubs installed.
Likely not a pandas-stubs issue, but just want to point out that it is also frustrating that the above error did not proper tracebacks to know that pandas-stubs was the library that caused it - I had trial and error with many individual scripts to reproduce it efficiently.

**Comment by hauntsaninja** [comment]
I wasn't able to repro:
```
λ uv pip freeze
Using Python 3.11.6 environment at /Users/shantanujain/.virtualenvs/tmpvenv-qscr
mypy==1.13.0
mypy-extensions==1.0.0
numpy==2.1.2
pandas-stubs==2.2.3.241009
pip==24.2
setuptools==75.1.0
types-pytz==2024.2.0.20241003
typing-extensions==4.12.2
wheel==0.44.0

λ mypy -c 'import pandas as pd'                      
Success: no issues found in 1 source file
mypy -c 'import pandas as pd'  2.10s user 0.29s system 17% cpu 13.914 total
```

Do you have a mypy config file or something?

**Comment by kristian4cast** [comment]
> Do you have a mypy config file or something?

For me, this issue occurs when follow imports is set to "error" (or "skip"),  i.e.
`mypy -c 'import pandas as pd' --follow-imports "error"` 
reproduces the error for me.

**Comment by Dr-Irv** [comment]
> For me, this issue occurs when follow imports is set to "error" (or "skip"), i.e. `mypy -c 'import pandas as pd' --follow-imports "error"` reproduces the error for me.

@hauntsaninja  I was able to reproduce in a clean environment, python 3.12, mypy 1.13.0 with latest `pandas-stubs`
```
mypy -c "import pandas as pd" --follow-imports "error"
Traceback (most recent call last):
  File "C:\Condadirs\envs\pandasstubstest\Scripts\mypy-script.py", line 10, in <module>
    sys.exit(console_entry())
             ^^^^^^^^^^^^^^^
  File "C:\Condadirs\envs\pandasstubstest\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 102, in main
  File "mypy\main.py", line 186, in run_build
  File "mypy\build.py", line 194, in build
  File "mypy\build.py", line 269, in _build
  File "mypy\build.py", line 2935, in dispatch
  File "mypy\build.py", line 3333, in process_graph
  File "mypy\build.py", line 3460, in process_stale_scc
  File "mypy\build.py", line 2497, in write_cache
  File "mypy\build.py", line 1559, in write_cache
  File "mypy\nodes.py", line 390, in serialize
  File "mypy\nodes.py", line 4010, in serialize
  File "mypy\nodes.py", line 3947, in serialize
  File "mypy\nodes.py", line 3371, in serialize
  File "mypy\types.py", line 682, in serialize
  File "mypy\types.py", line 2475, in serialize
  File "mypy\types.py", line 1498, in serialize
  File "mypy\types.py", line 682, in serialize
  File "mypy\types.py", line 3160, in serialize
AssertionError: Internal error: unresolved placeholder type None
```

**Comment by hauntsaninja** [comment]
Sounds like https://github.com/python/mypy/issues/17396

(Obligatory note: while this is certainly a bad bug, in my experience most people using a non-default value of `--follow-imports` are better served by not doing so)

**Comment by Dr-Irv** [comment]
Closing this issue here as it is a `mypy` issue, not a `pandas-stubs` issue.

**Comment by jindongyang94** [comment]
Thanks everyone! It is indeed a --follow-imports issue due to numpy2.0.0 (managed to reproduce the same error on my end).
