### ISSUE TITLE
BUG: loc.__getitem__ stricter than it should be with list indexers

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas-stubs#189]
**Describe the bug**

``loc.__getitem__`` is stricter than it should be I think

```
error: List item 0 has incompatible type "int"; expected "str"  [list-item]
error: List item 0 has incompatible type "None"; expected "str"  [list-item]

``` 

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
df = pd.DataFrame([[1, 2]], columns=Index([1, None], dtype=object))

df.loc[:, [None]]
df.loc[:, [1]]

```

Alternatively you could define df as 

```
df = pd.DataFrame({"a": [1, 2], None: 5})
```

Both of them should be valid. Especially since

```

df.loc[:, None]
df.loc[:, 1]

```

both work.

**Please complete the following information:**
 - OS:  ubuntu
 - OS Version 22.04
 - python version 3.10
 - version of type checker mypy 0.971
 - version of installed `pandas-stubs` newest 20220807

**Additional context**

**Comment by Dr-Irv** [comment]
Probably the same issue as in #188 - need to change `list[Optional[Hashable]]` to `list[HashableT]`

**Comment by phofl** [comment]
I think thats a bit different, the list elements are restricted to str, was this deliberate?

**Comment by Dr-Irv** [comment]
> I think thats a bit different, the list elements are restricted to str, was this deliberate?

No, it's just a result of how the types evolved over time by Microsoft.

I guess we have to change `StrLike` to `Hashable` or `HashableT` based on whether it is "alone" (use `Hashable`) or as a parameter to a type, e.g., `list[StrLike]` becomes `list[HashableT]`

**Comment by Dr-Irv** [comment]
So the code you gave with `None` as a column name doesn't work with pandas 1.4.3:
```python
>>> import pandas as pd
>>> df = pd.DataFrame({1: [1, 2], None: 5})
>>> df
   1.0  NaN
0    1    5
1    2    5
>>> df.loc[:, None]
Traceback (most recent call last):
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 144, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 20, in pandas._libs.index.Float64Engine._check_type
KeyError: None

>>> df.loc[:, [None]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 1149, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 827, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 1191, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 1132, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexing.py", line 1327, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexes\base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Anaconda3\envs\pandasstubs\lib\site-packages\pandas\core\indexes\base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index([None], dtype='object')] are in the [columns]"
```

**Comment by phofl** [comment]
It does, but you have to use different column names. You can either use a non integer as the other columns or do columns=Index([1, None], dtype=object)
